### ISSUE TITLE
right click paste doesn't open suggestions list

### ISSUE THREAD

**Issue by andrewharvey** [tristen/suggestions#16]
From https://github.com/mapbox/mapbox-gl-geocoder/issues/34#issuecomment-284948042, on Chrome, right click paste doesn't open suggestions list.

**Comment by zoephilipps** [comment]
@andrewharvey do you know of a workaround for this?

**Comment by andrewharvey** [comment]
@zackphilipps I've implemented a fix for this in #17. I'll see if there is any feedback or comments before merging.
