### ISSUE TITLE
release v1.3.2

### ISSUE THREAD

**Issue by andrewharvey** [tristen/suggestions#19]
There are [a few fixes not yet in a release](https://github.com/tristen/suggestions/commits/gh-pages) and I think we should do a release so https://github.com/mapbox/mapbox-gl-geocoder can pick up these fixes.

@tristen are you okay for me to do a release? Or can you do one?

Is this the process?

```
npm run test
npm run docs
npm run build
# update version number in package.json
# outline changes in CHANGELOG.md
git add -u
git commit -m 'v1.3.2'
git tag v1.3.2
git push upstream gh-pages --tags
npm publish
```

**Comment by tristen** [comment]
@andrewharvey great! What you outlined looks great and by all means!

**Comment by andrewharvey** [comment]
thanks @tristen, all done now.
