### ISSUE TITLE
add wrapper div to ul.suggestions to expand customization

### ISSUE THREAD

**Issue by katydecorah** [tristen/suggestions#27]
For mapbox-gl-geocoder, we'd like to append a link to the results so that users can submit search feedback. This is a little tricky right now because if we append this element to ul.suggestions, it'll get cleared out as the user is typing. Given that ul.suggestions is best absolutely positioned, it's difficult to get this new element positioned where we want it (just below ul.suggestions).

@tristen what do you think about a wrapper div for ul.suggestions? From my testing it should be a fairly quick add - I'd be happy to make this PR. Also open to other suggestions!

cc @scottsfarley93

**Comment by tristen** [comment]
@katydecorah 👍sounds good to me!
